name: "Code Style - PHP Mess Detector"

on:
  push:
    paths:
      - "**.php"
      - ".github/workflows/phpmd.yml"
  pull_request:
    paths:
      - "**.php"
      - ".github/workflows/phpmd.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.3
          version: dev-fix/throw-parsing
          path: src
          output: text
          ruleset: codesize,unusedcode,naming,design,controversial